"""empty message

Revision ID: d1e2b3cf7403
Revises: 3680b59de891
Create Date: 2023-10-24 03:36:00.248098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e2b3cf7403'
down_revision = '3680b59de891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('isbn', sa.String(length=120), nullable=False),
    sa.Column('pageCount', sa.Integer(), nullable=True),
    sa.Column('publishedDate', sa.DateTime(), nullable=True),
    sa.Column('thumbnailUrl', sa.String(length=200), nullable=False),
    sa.Column('shortDescription', sa.Text(), nullable=True),
    sa.Column('longDescription', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('authors', sa.String(length=200), nullable=True),
    sa.Column('categories', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('thumbnailUrl')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('follows_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_follow', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank_book',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('reads_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user')
    )
    op.create_table('review_book',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('xread_user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('xread_user')
    op.drop_table('review_book')
    op.drop_table('reads_users')
    op.drop_table('rank_book')
    op.drop_table('follows_users')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
